### ISSUE TITLE
Can't Import SSKR Bytewords from iOS Seedtool

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/seedtool-cli-rust#4]
Seedtool-CLI can't input one of the standard output methods for SSKR in Gordian Seedtool iOS:
```
$ seedtool -i sskr "leaf tuna news flew liar hard puma slot jade mild cyan belt axis diet epic zoom arch lazy yell crux vast work bald stub free warm arch acid omit keep luau liar vibe unit fern cola peck slot luau buzz hang loud many cola taco crux safe exam aunt when flap keys cusp owls each logo epic junk heat redo zero holy vast guru limp cost free quad wand wave hawk gala jugs city bias barn memo guru acid luck grim zero real into math cash drop jazz flux gala hill zone very mint easy calm jury jade aunt void draw lamb good fern obey noon knob flap very kick noon trip flew yell item claw gyro when vibe fuel kiln fact flux kiwi leaf figs apex tomb fizz warm wave puma jowl fair aqua iron high leaf rock leaf logo iron cola vibe nail gush flew cats wand hang soap taxi deli runs yank down real jowl work tied jade jugs logo saga gyro fuel owls math zinc keno jump plus silk swan girl code ramp ugly fern jowl ruby even note yurt gems list meow jugs calm hope flux main wasp slot edge judo tent good free maze lion vibe foxy yank draw yawn brew very road holy tent vast tied roof hard data tuna news flap hard crux road away frog zest curl blue cyan undo hill saga visa yawn liar surf holy epic roof pool quiz what eyes gift figs math half belt part idea iris inky days nail obey atom trip cats tuna next keep hard data frog yell able able able away menu cook diet cusp down logo work exit surf hawk fern dice days jowl axis zoom user ruin puff lamb monk toys away data item monk king cook owls inky trip list void user ugly"
Error: Could not parse input as SSKR shares
```

**Comment by shannona** [comment]
I think this is an SSKR of an Envelope, and that's likely what the issue is.

**Comment by wolfmcnally** [comment]
OK, the problem here was in the iOS app: we should *not* be supporting exporting envelope SSKR shares as ByteWords. The intent of ByteWords is to keep it short. So the fix is to modify the iOS app to *disallow* the export of SSKR shares as ByteWords, but only as ur:envelope. So now in the SSKR setup screen of the iOS app, if you choose the "Gordian Envelope" format, the next page no longer has the "All Shares as ByteWords" button, and the "Export Shares Individually" screen no longer offers ByteWords as an output format.

On the other hand, if you select "Legacy ur:sskr" as the format, the next page has "All Shares as ByteWords" and "All shares as Legacy ur:sskr", and the "Export Shares Individually" screen still has options for "UR" and "ByteWords". In other words, this remains unchanged.

The changes are in [this commit](https://github.com/BlockchainCommons/GordianSeedTool-iOS/commit/13a68e319d9973abd759dc5f6da08fb4f5dcdc77).
